samples/Standalone.MvcSample/Controllers/VerifyController.cs
using ActiveLogin.Authentication.BankId.Api;
using ActiveLogin.Authentication.BankId.Api.Models;

using Microsoft.AspNetCore.Mvc;

using Standalone.MvcSample.Models;

namespace Standalone.MvcSample.Controllers;

//
// DISCLAIMER
//
// These are samples on how to use Active Login in different situations
// and might not represent optimal way of setting up
// ASP.NET MVC or other components.
//
// Please see this as inspiration, not a complete template.
//

public class VerifyController : Controller
{
    private readonly IBankIdVerifyApiClient _bankIdVerifyApiClient;

    public VerifyController(IBankIdVerifyApiClient bankIdVerifyApiClient)
    {
        _bankIdVerifyApiClient = bankIdVerifyApiClient;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost("/verify/api")]
    public async Task<ActionResult<VerifyResultModel>> Verify([FromBody] VerifyRequestModel model)
    {
        ArgumentNullException.ThrowIfNull(model, nameof(model));
        if (string.IsNullOrEmpty(model.QrCodeContent))
        {
            throw new ArgumentNullException(nameof(model.QrCodeContent));
        }

        var verifyResult = await _bankIdVerifyApiClient.VerifyAsync(model.QrCodeContent);
        var user = verifyResult.User;
        var resultModel = new VerifyResultModel(user.PersonalIdentityNumber, user.GivenName, user.Surname, user.Name, user.Age, verifyResult.Authentication.GetIdentifiedAtDateTime(), verifyResult.Verification.GetVerifiedAtDateTime());

        return resultModel;
    }
}

samples/Standalone.MvcSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Active Login - Standalone.MvcSample</title>

    <!-- Manifest -->
    <link rel="manifest" href="/site.json?v=1">
    <meta name="msapplication-config" content="/browserconfig.xml?v=1">

    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/graphics/activelogin-apple-touch-icon.png?v=1">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/graphics/activelogin-favicon-32x32.png?v=1">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/graphics/activelogin-favicon-16x16.png?v=1">
    <link rel="mask-icon" href="/static/graphics/activelogin-safari-pinned-tab.svg?v=1" color="#5bbad5">
    <link rel="shortcut icon" href="/static/graphics/activelogin-favicon.ico?v=1">
    <meta name="apple-mobile-web-app-title" content="Active Login">
    <meta name="application-name" content="Active Login">
    <meta name="msapplication-TileColor" content="#008bc3">
    <meta name="theme-color" content="#ffffff">

    <!-- Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
        body {
            padding: 0 0 75px 0;
            background-color: #f5f5f5;
        }

        footer .navbar {
            background-color: #f5f5f5;
        }

        .choose-provider {
            width: 100%;
            max-width: 320px;
            margin: 0 auto;
            text-align: center;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .choose-provider a {
            text-align: center;
        }

        .choose-provider .choose-provider-logo {
            width: 133px;
            height: 133px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Standalone.MvcSample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sign" asp-action="Index">Sign</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Payment</a>
                        </li>
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Verify" asp-action="Index">Verify</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <nav class="navbar fixed-bottom navbar-light justify-content-center">
            <span class="navbar-text">
                <a href="https://activelogin.net">Powered by Active Login</a>
            </span>
        </nav>
    </footer>

    <!-- Scripts -->
    @RenderSection("Scripts", required: false)
</body>
</html>